### ISSUE TITLE
Bug: Rim of Madness Vampires causes mimic CanReach raise an error.

### ISSUE THREAD

**Issue by lag42** [Caaz/rimworld-typhon#96]
# Description
when [rim of madness - vampires](https://steamcommunity.com/sharedfiles/filedetails/?id=1187010034) is present what appears to be their job for vampires trying to stay under roofs prevents the mimic hiding job from working in a bizarre conflict
# Log
https://gist.github.com/HugsLibRecordKeeper/f70f91e6116cc952a1b05d54786b9fec

**Comment by Caaz** [comment]
Very interesting. I'll have to check out how their reach patch works. Might be patched so that vampires look for cover and for some reason it's affecting mimics somehow. It's probably affecting all Typhon. I'll take a look after work if I get the chance.

**Comment by Caaz** [comment]
Just as a follow up, this likely won't be something I solve on my end, because it's a patch caused in that mod for sure, and I don't even want to know what would happen if I try to patch a patch.

However I might wind up submitting a PR on that mod since it seems straightforward enough. But when it'll get resolved or fixed is out of my hands.

**Comment by Caaz** [comment]
And here's the PR to keep track of that
https://github.com/Rim-Of-Madness-Team/Rim-of-Madness---Vampires/pull/97

**Comment by Caaz** [comment]
Absolute hype, looks like this got [merged into the codebase](https://github.com/Rim-Of-Madness-Team/Rim-of-Madness---Vampires/pull/97#issuecomment-1165759225) and will be released soon. I'll go ahead and close this.
